### ISSUE TITLE
Handle passing query criteria by values 

### ISSUE THREAD

**Issue by WojciechMazur** [propensive/efflorescence#17]
Currently any try of passing filter or sort order by value/method would fail. 
Following code would fail:
```
val filterCriteria = _.foo > 1
val sortBy = _.bar

Dao[FooBar]
.filter(filterCritiera)
.sortBy(sortBy)()
```

In order to resolve such issue it is needed to resolve context of macro usage and obtain value definition.

**Comment by propensive** [comment]
We shouldn't do this: it's a step too far towards _interpreting_ the Scala code, and the further we push in this direction, the more problems we will encounter. The definition of `val filterCriteria` may actually be virtual, and therefore depend on the runtime type of the class, so in such cases we can't handle it correctly.

It's easiest to just add the restriction for these cases that we won't support them.
